version: '3.8'

services:
  web:
    build: ./django_prog_socialnetwork
    command: python manage.py runserver 0.0.0.0:8000 && python manage.py collectstatic
    volumes:
      - ./django_prog_socialnetwork:/django_prog_socialnetwork
    ports:
      - 8000:8000
    env_file:
      - env.dev
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env.db

volumes:
  postgres_data: